# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        JobZ\HomeBundle\Entity\User: plaintext
        Symfony\Component\Security\Core\User\User: plaintext
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded

    role_hierarchy:
        ROLE_ADMIN:             ROLE_USER
        ROLE_SUPER_ADMIN:       [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: admin, roles: [ 'ROLE_SUPER_ADMIN' ] }

        user:
            entity:
                class: HomeBundle:User
                property: email

        chain_provider:
            chain:
                providers: [in_memory, user]

    firewalls:
       main:
          pattern: ^/
          anonymous: ~
          provider: chain_provider
          form_login:
              login_path: jobz_home_login_login
              check_path: jobz_home_login_logincheck
          logout:
              path: jobz_home_login_logout
              target: jobz_home_job_index